server:
  port: 8080
  contextPath: /wishlist-srv
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/wishes
    driverClassName: org.postgresql.Driver
    username: wishes
    password: wishes
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework: ERROR