server:
  port: 8080

keycloak:
  realm: wishlist
  auth-server-url: http://localhost:8081/auth
  resource: wishlist-ui
  public-client: true
  ssl-required: external
  use-resource-role-mappings: false # we want to make sure realm roles are used
  principal-attribute: preferred_username
  cors: true

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://wishlist-db:5432/wishes
    url: jdbc:postgresql://localhost:5432/wishes
    username: wishes
    password: wishes
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.springframework: ERROR
    org.keycloak: DEBUG
    org.springframework.security: DEBUG