server:
  port: 8080
  servlet:
    context-path: /

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wishes
    username: wishes
    password: wishes
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.springframework: ERROR