apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: wishes
  POSTGRES_USER: wishes
  POSTGRES_PASSWORD: wishes
  PGDATA: /var/lib/postgresql/data/db-files/